In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [43]:
df=pd.read_csv('C:/Users/DELL/Documents/machine_learning/knn/lung_cancer_examples.csv')

In [44]:
df.dtypes

Name       object
Surname    object
Age         int64
Smokes      int64
AreaQ       int64
Alkhol      int64
Result      int64
dtype: object

In [45]:
df.columns

Index(['Name', 'Surname', 'Age', 'Smokes', 'AreaQ', 'Alkhol', 'Result'], dtype='object')

In [46]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [47]:
df.drop(['Name','Surname'],axis=1,inplace=True) 

In [48]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train

array([[26, 13,  6,  1],
       [73, 10,  7,  6],
       [36, 13,  5,  2],
       [42, 12,  6,  2],
       [39, 15,  7,  2],
       [77, 20,  5,  4],
       [39, 18,  8,  1],
       [52, 18,  4,  5],
       [34, 12,  8,  0],
       [37, 15,  6,  2],
       [42, 22,  3,  5],
       [77,  3,  2,  6],
       [62, 25,  3,  4],
       [75, 15,  3,  5],
       [47, 12,  8,  0],
       [18, 10,  6,  3],
       [47, 15,  1,  8],
       [26, 34,  1,  8],
       [50, 20,  2,  4],
       [62, 15,  5,  5],
       [40, 20,  2,  7],
       [63, 20,  4,  5],
       [27, 20,  2,  5],
       [33,  8,  8,  1],
       [30,  0,  5,  2],
       [31, 20,  9,  4],
       [37, 10,  5,  3],
       [25, 20,  8,  2],
       [44,  5,  8,  1],
       [53, 20,  6,  3],
       [33,  4,  8,  0],
       [22, 20,  6,  2],
       [62,  5,  4,  3],
       [51, 25,  9,  0],
       [55, 15,  1,  3],
       [22, 12,  5,  2],
       [69, 20,  5,  4],
       [34, 25,  4,  8],
       [55, 20,  1,  4],
       [44, 30,  1,  6],


In [50]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.15393627, -0.43269425,  0.40496913, -1.08797778],
       [ 1.7796194 , -0.84848639,  0.80993827,  1.1649055 ],
       [-0.52977549, -0.43269425,  0.        , -0.63740112],
       [-0.15527902, -0.57129163,  0.40496913, -0.63740112],
       [-0.34252726, -0.1554995 ,  0.80993827, -0.63740112],
       [ 2.02928371,  0.53748739,  0.        ,  0.26375219],
       [-0.34252726,  0.26029264,  1.2149074 , -1.08797778],
       [ 0.46888176,  0.26029264, -0.40496913,  0.71432885],
       [-0.65460765, -0.57129163,  1.2149074 , -1.53855444],
       [-0.46735941, -0.1554995 ,  0.40496913, -0.63740112],
       [-0.15527902,  0.81468215, -0.80993827,  0.71432885],
       [ 2.02928371, -1.81866804, -1.2149074 ,  1.1649055 ],
       [ 1.09304254,  1.23047428, -0.80993827,  0.26375219],
       [ 1.90445155, -0.1554995 , -0.80993827,  0.71432885],
       [ 0.15680137, -0.57129163,  1.2149074 , -1.53855444],
       [-1.6532649 , -0.84848639,  0.40496913, -0.18682447],
       [ 0.15680137, -0.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [52]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[11,  0],
       [ 1,  6]])

In [54]:
score=accuracy_score(y_test,y_pred)
score

0.9444444444444444