In [289]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [290]:
df=pd.read_csv('C:/Users/DELL/Documents/machine_learning/knn/stroke_prediction.csv')
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0           0.0            1.0          Yes        Private   
1       Male  80.0           0.0            1.0          Yes        Private   
2     Female  49.0           0.0            0.0          Yes        Private   
3     Female  79.0           1.0            0.0          Yes  Self-employed   
4       Male  81.0           0.0            0.0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0           0.0            0.0           No        Private   
4977    Male  40.0           0.0            0.0          Yes        Private   
4978  Female  45.0           1.0            0.0          Yes       Govt_job   
4979    Male  40.0           0.0            0.0          Yes        Private   
4980  Female  80.0           1.0            0.0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [291]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0           0.0            1.0          Yes        Private   
1    Male  80.0           0.0            1.0          Yes        Private   
2  Female  49.0           0.0            0.0          Yes        Private   
3  Female  79.0           1.0            0.0          Yes  Self-employed   
4    Male  81.0           0.0            0.0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [292]:
df.tail()

gender   age  hypertension  heart_disease ever_married work_type  \
4976    Male  41.0           0.0            0.0           No   Private   
4977    Male  40.0           0.0            0.0          Yes   Private   
4978  Female  45.0           1.0            0.0          Yes  Govt_job   
4979    Male  40.0           0.0            0.0          Yes   Private   
4980  Female  80.0           1.0            0.0          Yes   Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0

In [293]:
df.shape

(4981, 11)

In [294]:
df.dtypes

gender                object
age                  float64
hypertension         float64
heart_disease        float64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [295]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [296]:
df.isna().sum()

gender                0
age                   8
hypertension          3
heart_disease         3
ever_married          6
work_type            11
Residence_type        3
avg_glucose_level     6
bmi                   1
smoking_status        6
stroke                0
dtype: int64

In [297]:
df['age'].unique()

array([6.70e+01, 8.00e+01, 4.90e+01, 7.90e+01, 8.10e+01, 7.40e+01,
       6.90e+01, 7.80e+01, 6.10e+01, 5.40e+01, 5.00e+01, 6.40e+01,
       7.50e+01, 6.00e+01, 7.10e+01, 5.20e+01, 8.20e+01, 6.50e+01,
       5.70e+01, 4.20e+01, 4.80e+01, 7.20e+01, 5.80e+01,      nan,
       7.60e+01, 3.90e+01, 7.70e+01, 6.30e+01, 7.30e+01, 5.60e+01,
       4.50e+01, 7.00e+01, 5.90e+01, 6.60e+01, 4.30e+01, 6.80e+01,
       4.70e+01, 5.30e+01, 3.80e+01, 5.50e+01, 4.60e+01, 3.20e+01,
       5.10e+01, 1.40e+01, 3.00e+00, 8.00e+00, 3.70e+01, 4.00e+01,
       3.50e+01, 2.00e+01, 4.40e+01, 2.50e+01, 2.70e+01, 2.30e+01,
       1.70e+01, 1.30e+01, 4.00e+00, 1.60e+01, 2.20e+01, 3.00e+01,
       2.90e+01, 1.10e+01, 2.10e+01, 1.80e+01, 3.30e+01, 2.40e+01,
       3.60e+01, 6.40e-01, 3.40e+01, 4.10e+01, 8.80e-01, 5.00e+00,
       2.60e+01, 3.10e+01, 7.00e+00, 1.20e+01, 6.20e+01, 2.00e+00,
       9.00e+00, 1.50e+01, 2.80e+01, 1.00e+01, 1.80e+00, 3.20e-01,
       1.08e+00, 1.90e+01, 6.00e+00, 1.16e+00, 1.00e+00, 1.40e

In [298]:
df['age']=df['age'].fillna(df['age'].mean())

In [299]:
df['hypertension'].unique()

array([ 0.,  1., nan])

In [300]:
df['hypertension']=df['hypertension'].fillna(df['hypertension'].mode()[0])

In [301]:
df['heart_disease'].unique()

array([ 1.,  0., nan])

In [302]:
df['heart_disease']=df['heart_disease'].fillna(df['heart_disease'].mode()[0])

In [303]:
df['ever_married'].unique()

array(['Yes', 'No', nan], dtype=object)

In [304]:
df['ever_married']=df['ever_married'].fillna(df['ever_married'].mode()[0])

In [305]:
df['work_type'].unique()

array(['Private', 'Self-employed', 'Govt_job', nan, 'children'],
      dtype=object)

In [306]:
df['work_type']=df['work_type'].fillna(df['work_type'].mode()[0])

In [307]:
df['Residence_type'].unique()

array(['Urban', 'Rural', nan], dtype=object)

In [308]:
df['Residence_type']=df['Residence_type'].fillna(df['Residence_type'].mode()[0])

In [309]:
df['avg_glucose_level'].unique()

array([228.69, 105.92, 171.23, ..., 191.15,  95.02,  83.94], shape=(3890,))

In [310]:
df['avg_glucose_level']=df['avg_glucose_level'].fillna(df['avg_glucose_level'].mean())

In [311]:
df['bmi'].unique()

array([36.6, 32.5, 34.4, 24. , 29. , 27.4, 22.8, 24.2, 29.7, 36.8, 27.3,
       28.2, 30.9, 37.5, 25.8, 37.8, 22.4, 48.9, 26.6, 27.2, 23.5, 28.3,
       44.2, 25.4, 22.2, 30.5,  nan, 33.7, 23.1, 32. , 29.9, 23.9, 28.5,
       26.4, 20.2, 33.6, 38.6, 39.2, 27.7, 31.4, 36.5, 33.2, 32.8, 40.4,
       25.3, 30.2, 47.5, 20.3, 30. , 28.9, 28.1, 31.1, 21.7, 27. , 24.1,
       45.9, 44.1, 22.9, 29.1, 32.3, 41.1, 25.6, 29.8, 26.3, 26.2, 29.4,
       24.4, 28. , 28.8, 34.6, 19.4, 30.3, 41.5, 22.6, 27.1, 31.3, 31. ,
       31.7, 35.8, 28.4, 20.1, 26.7, 38.7, 34.9, 25. , 23.8, 21.8, 27.5,
       24.6, 32.9, 26.1, 31.9, 34.1, 36.9, 37.3, 45.7, 34.2, 23.6, 22.3,
       37.1, 45. , 25.5, 30.8, 37.4, 34.5, 27.9, 29.5, 46. , 42.5, 35.5,
       26.9, 45.5, 31.5, 33. , 23.4, 30.7, 20.5, 21.5, 40. , 28.6, 42.2,
       29.6, 35.4, 16.9, 26.8, 39.3, 32.6, 35.9, 21.2, 42.4, 40.5, 36.7,
       29.3, 19.6, 18. , 17.6, 17.7, 35. , 22. , 39.4, 19.7, 22.5, 25.2,
       41.8, 23.7, 24.5, 31.2, 16. , 31.6, 25.1, 24

In [312]:
df['bmi']=df['bmi'].fillna(df['bmi'].mean())

In [313]:
df['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown', nan],
      dtype=object)

In [314]:
df['smoking_status']=df['smoking_status'].fillna(df['smoking_status'].mode()[0])

In [315]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['gender']=lab.fit_transform(df['gender'])

In [316]:
df['ever_married']=lab.fit_transform(df['ever_married'])

In [317]:
df['work_type']=lab.fit_transform(df['work_type'])

In [318]:
df['Residence_type']=lab.fit_transform(df['Residence_type'])

In [319]:
df['smoking_status']=lab.fit_transform(df['smoking_status'])
df['age']=lab.fit_transform(df['age'])
df['hypertension']=lab.fit_transform(df['hypertension'])
df['heart_disease']=lab.fit_transform(df['heart_disease'])
df['avg_glucose_level']=lab.fit_transform(df['avg_glucose_level'])
df['bmi']=lab.fit_transform(df['bmi'])
df.dtypes

gender               int64
age                  int64
hypertension         int64
heart_disease        int64
ever_married         int64
work_type            int64
Residence_type       int64
avg_glucose_level    int64
bmi                  int64
smoking_status       int64
stroke               int64
dtype: object

In [320]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [321]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
x_train

array([[   1,   33,    0, ..., 3461,   56,    0],
       [   0,   60,    0, ..., 2261,  278,    2],
       [   1,   69,    0, ..., 2655,  197,    0],
       ...,
       [   1,  104,    0, ...,  711,  130,    1],
       [   0,   26,    0, ..., 1752,   66,    0],
       [   0,   69,    0, ..., 2343,  113,    0]], shape=(3486, 10))

In [322]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train,y_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[ 1.16148896, -1.35940045, -0.32928115, ...,  1.47043349,
        -1.3044351 , -1.27910433],
       [-0.86096384, -0.21314616, -0.32928115, ...,  0.36338669,
         1.94685121,  0.59558883],
       [ 1.16148896,  0.16893861, -0.32928115, ...,  0.72686705,
         0.76057107, -1.27910433],
       ...,
       [ 1.16148896,  1.6548238 , -0.32928115, ..., -1.06654877,
        -0.22067299, -0.34175775],
       [-0.86096384, -1.65657749, -0.32928115, ..., -0.10618567,
        -1.15798076, -1.27910433],
       [-0.86096384,  0.16893861, -0.32928115, ...,  0.43903488,
        -0.46964537, -1.27910433]], shape=(3486, 10))

In [323]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(1495,))

In [324]:
y_test

array([0, 0, 0, ..., 0, 0, 0], shape=(1495,))

In [325]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1408,   10],
       [  74,    3]])

In [326]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.9438127090301003