In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
df=pd.read_csv('C:/Users/DELL/Documents/machine_learning/knn/weather_prediction_dataset.csv')

In [15]:
df.columns

Index(['DATE', 'MONTH', 'BASEL_cloud_cover', 'BASEL_humidity',
       'BASEL_pressure', 'BASEL_global_radiation', 'BASEL_precipitation',
       'BASEL_sunshine', 'BASEL_temp_mean', 'BASEL_temp_min',
       ...
       'STOCKHOLM_temp_min', 'STOCKHOLM_temp_max', 'TOURS_wind_speed',
       'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation',
       'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min',
       'TOURS_temp_max'],
      dtype='object', length=165)

In [16]:
df.dtypes

DATE                        int64
MONTH                       int64
BASEL_cloud_cover           int64
BASEL_humidity            float64
BASEL_pressure            float64
                           ...   
TOURS_global_radiation    float64
TOURS_precipitation       float64
TOURS_temp_mean           float64
TOURS_temp_min            float64
TOURS_temp_max            float64
Length: 165, dtype: object

In [17]:
df.isna().sum()

DATE                      0
MONTH                     0
BASEL_cloud_cover         0
BASEL_humidity            0
BASEL_pressure            0
                         ..
TOURS_global_radiation    0
TOURS_precipitation       0
TOURS_temp_mean           0
TOURS_temp_min            0
TOURS_temp_max            0
Length: 165, dtype: int64

In [18]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)
x_test

array([[-0.53101463,  1.00749679,  1.1030362 , ...,  1.21128705,
        -0.27550942,  0.1094472 ],
       [-0.90964322, -1.5703911 ,  1.1030362 , ..., -0.42991161,
        -0.5992158 , -0.5410139 ],
       [-1.23587728,  0.14820083, -0.60581782, ...,  2.57895261,
         0.71102432,  0.90054854],
       ...,
       [ 1.53350359, -0.42466315, -1.88745834, ..., -0.42991161,
         0.66478055,  0.30282753],
       [-0.19121351,  0.43463282,  0.6758227 , ...,  0.02597691,
         1.09638906,  1.34004928],
       [ 0.82884912, -1.28395911,  0.6758227 , ..., -0.1563785 ,
        -0.66087416, -0.69923417]], shape=(1097, 164))

In [26]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor(n_neighbors=7)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([11.18571429,  9.8       , 22.88571429, ..., 22.82857143,
       23.37142857, 12.62857143], shape=(1097,))

In [27]:
y_test

array([12.2, 11.6, 20.5, ..., 23.2, 22.9, 11.9], shape=(1097,))

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
cm

ValueError: continuous is not supported